[package]
name = "cli"
version = "0.0.0"
edition = "2021"

[dependencies]
cloudagent-python = { path = "../cloudagent-python" }
agent = { path = "../agent" }
automations = { path = "../automations" }
logger = { path = "../logger" }
base64 = "0.13.0"
clap = { version = "3.1.0", features = ["derive"] }
clipboard = "0.5.0"
colored = "2.0.0"
qr2term = "0.2.2"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_yaml = "0.8.23"
tokio = { version = "1", features = ["full"] }
