[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.51"
reqwest = {version = "0.11", features = ["json"]}
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.68"
