name: E2E tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
      - uses: actions/checkout@v2
      - name: Start acapy
        run: docker-compose -f ./docker/docker-compose.acapy.min.yml up -d
      - name: Build siera
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: E2E tests
        run: make e2e-test
